### ISSUE TITLE
Firefox with Enhanced Tracking Protection throws SecurityError

### ISSUE THREAD

**Issue by StanAngeloff** [SecureTrading/js-payments#1086]
Hello,

When using Firefox 77 (the latest as of June 2020) with the default Enhanced Tracking Protection left turned on, using the JavaScript integration results in a `SecurityError: The operation is insecure.` I can confirm disabling Enhanced Tracking Protection prevents this error from appearing.

I've reported this to Mozilla on a few occasions/websites.

The issue is triggered when trying to access `window.localStorage`. The full stack track is included below:

```
SecurityError: The operation is insecure. controlFrame.js:16
    n https://webservices.securetrading.net/js/v2/controlFrame.js:16
    bind_constructFunctionN self-hosted:1068
    n self-hosted:1005
    getServiceValue https://webservices.securetrading.net/js/v2/controlFrame.js:16
    get https://webservices.securetrading.net/js/v2/controlFrame.js:16
    initializeParams https://webservices.securetrading.net/js/v2/controlFrame.js:16
    map self-hosted:240
    initializeParams https://webservices.securetrading.net/js/v2/controlFrame.js:16
    getServiceValue https://webservices.securetrading.net/js/v2/controlFrame.js:16
    get https://webservices.securetrading.net/js/v2/controlFrame.js:16
    get https://webservices.securetrading.net/js/v2/controlFrame.js:16
    <anonymous> https://webservices.securetrading.net/js/v2/controlFrame.js:39
    n https://webservices.securetrading.net/js/v2/controlFrame.js:1
    <anonymous> https://webservices.securetrading.net/js/v2/controlFrame.js:39
    n https://webservices.securetrading.net/js/v2/controlFrame.js:1
    <anonymous> https://webservices.securetrading.net/js/v2/controlFrame.js:1
    <anonymous> https://webservices.securetrading.net/js/v2/controlFrame.js:1
    <anonymous> https://webservices.securetrading.net/js/v2/controlFrame.js:1
    <anonymous> https://webservices.securetrading.net/js/v2/controlFrame.js:1
```

There's [more information](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy#:~:text=localStorage) on Mozilla's website.

**Comment by james-simpson-ST** [comment]
Hello Stan,

Thank you for raising this, we already plan to move away from `window.localStorage` in a future update, in our case we are not using this to track users activity but within the payment process itself. However, as we are considered the third-party as our library is included within a merchants web application; and there's no way for the browser to infer intent; this is flagged by Firefox.

Currently, this does not cause an issue as it is only a warning but as the article states: 

> This policy does not currently restrict third-party storage access for resources that are not classified as tracking resources. We may choose to apply additional restrictions to third-party storage access in the future.

So we will ensure we work this into a future release
