### ISSUE TITLE
No way to refresh a JWT token

### ISSUE THREAD

**Issue by chernovol** [SecureTrading/js-payments#444]
No way to refresh a JWT token, which means:

**1.** impossible to have a single page where the user types their billing address and choose a payment amount.

**2.** impossible to refresh a JWT token when it's expired, so if user stuck on the payment page longer than 15 minutes we will need to ask them to refresh a page into web browser

**Comment by james-simpson-ST** [comment]
Thanks for the feedback, these sound like nice enhancements and we will look at adding an updateJWT functionality which can be used to update this.

JWTs should always be generated by your server to protect the shared secret but this could be done via an ajax call to get a new JWT when the user chooses the payment amount/after 15 minutes. If we expose a function to allow you to update the JWT I think this would allow both scenarios you described above

**Comment by chernovol** [comment]
Yep, ability to refresh a token will solve both issues,
would be great to get such ability in the nearest future.
Thanks for the quick reply.

**Comment by chernovol** [comment]
Hi @james-simpson-ST, any status update on this issue?

**Comment by james-simpson-ST** [comment]
Hi @chernovol this feature has been implemented in v2.0.1 of our library, this will be deployed to our webservices endpoint in the next release (date TBD). I will update once we have a schedule for this release.

**Comment by chernovol** [comment]
Hi @james-simpson-ST 
any news regarding the release of the feature?

**Comment by chernovol** [comment]
any update?

**Comment by james-simpson-ST** [comment]
Hi @chernovol sorry for the delay, we have now released this feature and here is a new documentation page outlining how to use it https://docs.securetrading.com/document/toolbox/update-jwt/
