### ISSUE TITLE
Incompatible with React due to duplicate event listeners

### ISSUE THREAD

**Issue by kirsty-forrester** [SecureTrading/js-payments#565]
Great work on this library. I appreciate that it isn’t designed for React, but it’s very close to working with it. There’s just one issue:

The first payment correctly submits one time, but each time we render the form (client-side), more songbird.js script tags are added to the head (see screencap). Then because there’s an on load event listener for the songbird scripts, some methods - including CardinalCommerce _authorizePayment - are called repeatedly when the form is submitted, resulting in duplicate transactions.

Each subsequent form submission results in more songbird.js scripts and an increasing number of duplicated transactions. There are ways of working around it, sort of, but the solutions are far from ideal, e.g. force refreshing the page or keeping the form component mounted but hidden. The latter solution doesn't work for us because we have two separate payment forms on our site.

I’m not sure what the best solution is, possibly preventing duplicate scripts and event listeners or exposing a method so that we can remove them.

Considering how popular React and similar JS frameworks are, I believe this is worth looking into. We may eventually be forced to switch to a different payment processor if this can’t be resolved. Thank you.

![Screen Shot 2019-11-26 at 14 39 32](https://user-images.githubusercontent.com/2790243/69795296-d18a0600-11c3-11ea-90ae-77b5ec8da456.png)

**Comment by james-simpson-ST** [comment]
Thanks for taking the time to provide us feedback, I agree supporting React (and other similarly popular frameworks Angular/Vue etc) would be something we would like to support going forward.

I think we can probably do something inside our library using the lodash._once function https://lodash.com/docs/4.17.15#once or similar
I have added this into our backlog to investigate

**Comment by pgs-gmartowski** [comment]
@kirsty-forrester Which version of ReactJS you're using in your project ? Is this Single Page Application ?

**Comment by kirsty-forrester** [comment]
@pgs-gmartowski Yes, it's a single page application with client-side rendering. It's currently using React 16.4.2 but we will be upgrading it soon.

**Comment by james-simpson-ST** [comment]
Hi @kirsty-forrester we've looked into this and have implemented the necessary destroy functionality to prevent duplicate event listeners.
We have also implemented a check so not to add duplicated songbird.js scripts.

This should mean you are now able to use our library within a Single Page Application using tools like React :smile:
