### ISSUE TITLE
HTML5 validation of form fields

### ISSUE THREAD

**Issue by StanAngeloff** [SecureTrading/js-payments#926]
Hi there :wave:

I'm trying to add an additional required field to the example like so:

```html
<form id="st-form" action="https://www.example.com" method="POST">

    <!-- 𝐓𝐇𝐈𝐒: -->
    <input type="text" name="field1" required>

    <div id="st-card-number" class="st-card-number"></div>
    <div id="st-expiration-date" class="st-expiration-date"></div>
    <div id="st-security-code" class="st-security-code"></div>
    <button type="submit" id="st-form__submit" class="st-form__submit">
        Pay securely
    </button>
</form>
```

However HTML5 validation is bypassed when clicking the Pay button or pressing the <kbd>Enter</kbd> key.

Does the JS library support additional form fields with HTML5 validation or should the form be EXCLUSIVELY for payments?

I've looked at the various callbacks, but they all fire after a submit. As a workaround, is it possible to call a custom function before `_onSubmit` is executed?

**Comment by eilianST** [comment]
Please ensure that you have an **id** and **data-st-name** property on your custom field to ensure HTML5 validation e.g.

<input id="field1" type="text" data-st-name="field1" required="">

**Comment by StanAngeloff** [comment]
Thanks @eilianST. Looks like this may work, but the field cannot be any field we want, it has to match the spec. We've worked around the issue by splitting the form in two steps, step 1 is the fields we collect and wish to validate and step 2, a stand-alone payment form.
